version: "3"
services:
  # Application
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=maslweb"
    ports:
      - "9000:9000"
    links:
      - database

  # Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app

  # Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: maslweb
      MYSQL_USER: maslweb
      MYSQL_PASSWORD: maslweb
      MYSQL_ROOT_PASSWORD: root

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

volumes:
  dbdata:
